# Generated by Django 4.0.6 on 2022-08-25 14:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('date', models.DateField(default=datetime.date(2022, 8, 25), primary_key=True, serialize=False)),
                ('n_completed', models.IntegerField()),
                ('n_expired', models.IntegerField()),
                ('n_querying', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
