# Generated by Django 4.0.6 on 2022-08-27 17:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_date', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date(2022, 8, 27))),
                ('n_completed', models.IntegerField(default=0)),
                ('n_expired', models.IntegerField(default=0)),
                ('n_querying', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
