# Generated by Django 4.0.6 on 2022-08-27 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='user_date',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='date',
            field=models.DateField(default=datetime.date(2022, 8, 27)),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='n_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='n_expired',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='n_querying',
            field=models.IntegerField(default=0),
        ),
    ]
