# Generated by Django 4.0.6 on 2022-08-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_dailyprogress_user_date_alter_dailyprogress_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyprogress',
            name='user_date',
            field=models.CharField(max_length=100),
        ),
    ]
