# Generated by Django 4.0.6 on 2022-08-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('OP', 'On progress'), ('C', 'Completed'), ('E', 'Empty')], default='E', max_length=2),
        ),
    ]
