# Generated by Django 4.0.6 on 2022-08-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_progress_alter_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
