# Generated by Django 4.0.6 on 2022-08-21 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_category_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
