# Generated by Django 4.0.6 on 2022-08-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('2', 'On progress'), ('3', 'Completed'), ('1', 'Empty')], default='1', max_length=4),
        ),
    ]
