# Generated by Django 4.0.6 on 2022-08-07 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 7, 17, 21, 41, 10537, tzinfo=utc), null=True),
        ),
    ]
