# Generated by Django 4.0.6 on 2022-08-09 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_dead_line_date_task_dead_line_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dead_line_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='dead_line_time',
        ),
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
