# Generated by Django 4.0.6 on 2022-08-09 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
