# Generated by Django 4.0.6 on 2022-08-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_task_dead_line'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('dead_line',)},
        ),
    ]
